### PR TITLE
Update SparkFunBME280.cpp

### PR DESCRIPTION
**Pull request by LukaGitH**
Added force update mode

### CODE REVIEW

**Comment by nseidle** [comment]
Hi LukaGitH,

Thanks for this but I have a question:

Table 25 in datasheet says forced mode is 01 or 10. Your code sets the last bit which is fine but doesn't guarantee that Forced mode will be entered. Don't you need to clear bits 0 and 1 and then set bits 0 and 1?

**Comment by nseidle** [comment]
Also, if you've got a test sketch you're running against I'd love to use it as well.

**Comment by LukaGitH** [comment]
Hi nseidle,
Yes you are right, you have 4 possible values for 3 possible states and like you said 01 and 10 are for forced. 
What you say is true, but if you think about it, you either come from 11 (normal) state, 00 (sleep) state or from 01 (forced) state. 
If you start from 00, 01 or 10, you'll always be in sleep mode after reading, only if you have set your settings to 11, you will stay in 11, but then you don't need forced reading

I'll clean up one of the sketches, since it use many different items in it.

I can also look into first clearing bits, before setting them

**Comment by LukaGitH** [comment]
Did you give it a try?

**Comment by nseidle** [comment]
Hi Luka, I have overhauled the lib to include a setMode() function. You can use it by calling 

    mySensor.setMode(MODE_FORCED); 

I will try to write an example demonstrating this function as well.

**Pull request closed without merging**
