### PR TITLE
Added ability to select Wire bus in begin function

### PR DESCRIPTION
**Pull request by mjs513**
Added ability to select wire bus in setup.
1. mySensor.begin() defaults to Wire
2. mySensor.begin(&Wire1) sets I2C to use Wire1
3. mySensor.begin(&Wire2) sets I2C to use Wire2

Also incorporated Pull Request 8.

Hope this helps someone.
Mike

### CODE REVIEW

**Comment by nseidle** [comment]
I like this feature a lot. I think all libraries should have the Wire stream passed to it as an option. However, your PR seems to include a lot of other small changes that have me worried. Why did you change [this line](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/pull/11/files#diff-3b4258f48aec80be39d431072f724bc2L132) (variable declare of dig_H6)?

**Comment by nseidle** [comment]
I see why you changed H6 - explained in a previous [PR](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/pull/8). There's still a lot of changes that are not Wire stream related in your PR. Can you either submit a new one or help me understand your other changes?

**Comment by mjs513** [comment]
Hi Nathan 
Sorry for the delay in responding - had to go look at what I changed,  its been awhile since I looked at it :).  Anyway in going back over the changes anything not stream related came from the PR#8.  Just had to do a sanity check before I responded.  There should be no other changes.

The line you referenced comes directly from PR#8 which I see you merged already.

Mike

**Comment by nseidle** [comment]
Hi Mike - Thanks for this PR. I have implemented the core of your idea but rolled it into a larger overhaul of the library. We should have a v2.0 of the lib available soon with examples showing how to use other Wire ports.

**Pull request closed without merging**
